export default {
  icHumberIcon: require('../assets/images/hamburger-icon.png'),
  icBackIcon: require('../assets/images/left-arrow.png'),
  profileIcon: require('../assets/images/profile-icon.png'),
  ic_Profile_Image: require('../assets/images/pp.png'),
  cartBasket: require('../assets/images/cartimage.jpg'),
  privacyIcon: require('../assets/images/privacy.png'),
  historyIcon: require('../assets/images/history.png'),
  rightArrow: require('../assets/images/right-arrow.png'),
  helpSupport: require('../assets/images/help-support.png'),
  setting_icon: require('../assets/images/setting-icon.png'),
  invite_icon: require('../assets/images/invite.png'),
  logoutIcon: require('../assets/images/logout-icon.png'),
  cartIcon  : require ('../assets/images/cart-icon.png'),
   searchIcon : require('../assets/images/search-icon.png'),
   logoIcon : require ('../assets/images/logo-icon.png'),
   homeIcon : require ('../assets/images/Home.png'),
   loginImage: require ('../assets/images/login-image.png'),
  cartItemImage : require ('../assets/images/carthomeicon.png'),
  profileImage : require ('../assets/images/profile.png'),
     bgc : require('../assets/images/bgc.png'),
     emailLogo: require('../assets/images/email-logo.png'),
     passwordIcon : require ("../assets/images/password-icon.png"),
     cartHomeIcon: require ('../assets/images/carthomeicon.png')
};
